# Generated by Django 3.1.7 on 2021-03-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='logs',
            new_name='habit',
        ),
    ]
