# Generated by Django 3.1.7 on 2021-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_auto_20210307_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
