# Generated by Django 3.1.7 on 2021-03-24 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_auto_20210324_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='habit',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
